### ISSUE TITLE
PPPoE IPv6 Problem

### ISSUE THREAD

**Issue by matthias-zivim** [xvzf/zyxel-gpon-sfp#15]
I have been using the Zyxel GPON SFP module quite successfully for a few days. However, with one problem.
I do not get an IPv6 address from the ISP (Telekom).

When I do the PPPoE dial-up on the Draytek 2962 / 3910 via a copper WAN port on the ONT (fiber modem), I get an IPv4 and IPv6 address.

Ex.
[IPv6] WAN5 IPv6 PPP Open
[IPv6] WAN5, Type(PPP), Rx EVENT = EVT_PFX_DELEGATE_ACTIVE
[DHCPv6c] Send solicit to FF02::1:2 on WAN5
[DHCPv6c] Receive advertise from ... on WAN5
[DHCPv6] Client DUID:
...
[IPv6] IPv6 WAN5 up (DHCPv6)!
[IPv6] IPv6 WAN5 UP!!!
[IPv6] WAN5, Type(PPP), Rx EVENT = EVT_RA_ACTIVE

All OK

If I use the Zyxel GPON SFP module:

[IPv6] WAN2 IPv6 PPP Open
[IPv6] WAN2, Type(PPP), Rx EVENT = EVT_PFX_DELEGATE_ACTIVE
[DHCPv6c] Send solicit to FF02::1:2 on WAN2
[DHCPv6c] Send solicit to FF02::1:2 on WAN2
[DHCPv6c] Send solicit to FF02::1:2 on WAN2
[DHCPv6c] Send solicit to FF02::1:2 on WAN2
[DHCPv6c] Send solicit to FF02::1:2 on WAN2
[IPv6] WAN2, Type(PPP), Rx EVENT = EVT_TIME_OUT
[IPv6] IPv6 event timeout (DHCPv6, 15 sec)!
[IPv6] WAN2, Type(PPP), Rx EVENT = EVT_PFX_DELEGATE_DOWN

Could it be a MTU problem?

ZYXEL# hal
Hal# mtu read 1518 -> too large?

Hal# mtu write 1492 -> no effect

﻿A request to Draytek is in progress

Thanks

**Comment by matthias-zivim** [comment]
The interfaces of the Draytek 3910 behave differently. IPv6 works in the WAN1 port.
Only the WAN2 haven causes problems.
The configuration is of course identical 🤔

**Comment by bentau** [comment]
@matthias-zivim did you find a solution for that problem?

**Comment by matthias-zivim** [comment]
Unfortunately, no solution was found. Draytek Germany did not want to understand me and only wanted to talk about why you have to use a GPON SFP module!? This possibility is unknown.
Years have passed since then. Perhaps draytek now knows GPON SFP modules

**Comment by bentau** [comment]
To me it looks like the Zyxel GPON SFP does something wrong and does not forward any IPv6 traffic. My German ISP also confirmed that they don't see any DHCPv6 solicit message from me. 
I tested the SFP in a mikrotik router and a TPLink media converter.
I order a different SFP module from fs.com and hope that this will work.

**Comment by kbabioch** [comment]
Very interested in the results with the other module. Seems like we have only limited options with GPON / Mikrotik. I'm also @ Deutsche Telekom, but my module is not detected at all (see #37). I've ordered some used ones from Italy via eBay, hoping to get some older firmware this way. Let's wait and see until they do arrive ;-).

**Comment by bentau** [comment]
The fs.com module arrived and everything (including ipv6) just works out of the box.
So something seems to be broken with the ipv6 support of those telekom modules, at least with my local ISP (not Telekom).

**Comment by kbabioch** [comment]
Which module exactly do you have? And can you set / fake the `PLOAM/SLID/Installationskennung` (similar to the Zyxel device)?

**Comment by bentau** [comment]
@kbabioch i got this one https://www.fs.com/de/products/183843.html Customized 1.25G/2.5G GPON SFP ONU Stick with Mac
When you order it, you tell them the SLID and the mac address that you want.
