### ISSUE TITLE
No more access to module after setting speed to 2.5G

### ISSUE THREAD

**Issue by umatz** [xvzf/zyxel-gpon-sfp#19]
Maybe someone might have a hint for me...

After finally getting my ftth line activated by the ISP I was able to access the module on 10.10.1.1 (it sits in a MikroTik RB2011 router), no access before without an active fiber.
After a little digging around I decided to set the interface speed do 2.5G with 
`ZYXEL# hal
Hal# set speed 2.5g mode full`
because I hat noticed that the fiber speed was announced with 2.5G capacity.
After executing the command I can longer access the module on 10.10.1.1.
Apparently the above command sets the speed on the internal/LAN side and not on the fiber/WAN side and I have now locked out access to the module because the routers SFP-Slot does not support 2.5 ethernet?

I already tried to disable auto negotiation and set fixed speeds of 1G and 2.5G but I cannot ping the module anymore.
I am not sure if PPPoE-Client would work now on this interface in this state and if I have bricked the module.

Any idea?

**Comment by jaseg** [comment]
IIRC the module uses an SPI flash IC for the root file system. One way to recover would be to do what the coreboot people do, and hook up that IC to a raspberry pi using some temporarily soldered wires. Then you would be able to read out, modify, and re-flash the IC.

**Comment by poshul** [comment]
There's also a serial connection on the board: https://github.com/hack-gpon/hack-gpon.github.io/blob/main/_ont/ont-zyxel-pmg3000-d20b.md. You can hook up with a buspirate or equivalent.

**Comment by umatz** [comment]
Thanks for for answers. I will try to get access via serial console, information of how to do so is a little sparse.

**Comment by umatz** [comment]
I was not able to obtain information on how to connect a serial console on this module. The two marked pads are Rx/Tx but I do not know where to get Ground and Vcc (3,3V)
![IMG_2037](https://user-images.githubusercontent.com/1059844/234301748-69c66b80-0024-4e9a-a12e-2b7b93ba92d2.jpeg)
Meanwhile I bought a second module, configured the serial number and am now online with IP DNS:NET.
I will close this ticket as it is no "bug".

**Comment by jaseg** [comment]
All of the metal is ground, and VCC is probably most easily accessible on the 8-pin SPI flash, the big chip labelled "GigaDevice" in your picture. Here's a datasheet of the chip [link](https://www.gigadevice.com.cn/Public/Uploads/uploadfile/files/20220714/DS-00111-GD25Q64C-Rev3.2.pdf), VCC is on pin 8, the top right pin in your picture.

**Comment by umatz** [comment]
I just wanted to let the interested know that I was successful. I forgot to take a photo but after removing the pcb completely from the sfp case I got access to the other side of the sfp 'header'. The two middle pins are VCC 3.3V and the two outer pins on each edge are GND.
After soldering an USB-serial adapter to the four pins I got access to a full serial console, could watch the boot process and logon to the system (exactly like vie ssh).
I could set the speed back to the default values with 
`Hal# set speed default mode default`

**Comment by kayrus** [comment]
> Meanwhile I bought a second module, configured the serial number and am now online with IP DNS:NET
@umatz, I'd like to connect to DNS:NET with this module as well. Can you clarify is it necessary to change the serial number to get connected to DNS:NET? Where can I find this serial number?

**Comment by umatz** [comment]
Hi @kayrus ,

I have a passive fibertwist and got a FritzBox 5530 from DNS:NET (fiber optic cable between fibertwist and fritz box). I extracted the gpon_serial from the FritzBox (via a diagnosis dump) and set the "PON SN" of the Zyxel sfp module to the same value. Thus I could connect to DNS:NET without any changes necessary on their side. I think I didn't changed the PLOAM password, in my Zyxel module it is set to 'default'.

**Comment by kayrus** [comment]
thanks, @umatz. I'll try it once I get an SFP module.

>  I do not know where to get Ground and Vcc (3,3V)

ground is usually linked with the shell. Vcc usually can be ignored, since 3.3V USB UART controllers get power from the USB. Do you still own a broken module?

**Comment by umatz** [comment]
> Do you still own a broken module?

No, see my comment directly above your first question, I was able to reset the speed after successfully connecting an USB-adapter, so i have now two working adapters.

**Comment by kayrus** [comment]
> No, see my comment directly above your first question

oh, somehow I missed this. Too much information about the GPON and SFP was read meanwhile

**Comment by motorsense** [comment]
Hello,
i have also set it to 2,5G. Then no connection problem.  (X520 Card)
I have solve it with a cheap China switch with SFP+ ports. (ZX-SWTG124AS)
-Set the port speed of SFP+ at the switch manualy to 2,5G
-configure Port mirror  SFP+ port to PC port on switch
-then i configure my pc address to 10.10.1.2/24
-i can connect via SSH to the module

I hope it can help others

**Comment by SaulGoodman1337** [comment]
```
#!/usr/bin/env bash
# Requirements: sudo apt-get install -y sshpass expect

HOST="10.10.1.1"
SSH_USER="admin"
SSH_PASS="admin"
CLI_USER="admin"
CLI_PASS="1234"

while true; do
expect <<EOF
    set timeout 20
    log_user 0

    # SSH login (optimized, faster handshake)
    spawn sshpass -p "${SSH_PASS}" ssh -tt \
        -o StrictHostKeyChecking=no \
        -oHostKeyAlgorithms=+ssh-rsa \
        -o PreferredAuthentications=password \
        -o PubkeyAuthentication=no \
        -o GSSAPIAuthentication=no \
        -o KbdInteractiveAuthentication=no \
        -o NumberOfPasswordPrompts=1 \
        -o ConnectionAttempts=1 \
        -o ConnectTimeout=1 \
        ${SSH_USER}@${HOST}

    # Second login (device CLI login)
    expect {
        "Login:" {}
        timeout { exit 1 }
        eof     { exit 1 }
    }
    after 10
    send -- "${CLI_USER}\r"

    expect {
        "Password:" {}
        "Invalid login name" { exit 1 }
        timeout { exit 1 }
        eof     { exit 1 }
    }
    after 10
    send -- "${CLI_PASS}\r"

    # After CLI login: either already in Hal# prompt or still in ZYXEL# prompt
    set in_hal 0
    expect {
        -re {Hal#}   { set in_hal 1 }
        -re {ZYXEL#} { set in_hal 0 }
        timeout { exit 1 }
        eof     { exit 1 }
    }

    log_user 1

    # Only enter HAL mode if not already in Hal#
    if { \$in_hal == 0 } {
        send -- "\r"
        expect -re {ZYXEL#}
        send -- "hal\r"
        expect -re {Hal#}
    }

    # Send the target command + extra Enter
    send -- "set speed default mode default\r"
    send -- "\r"
    expect -re {Hal#}

    # Hand over to interactive mode
    interact
    exit 0
EOF

    # Retry every 0.1 seconds until successful
    if [ $? -ne 0 ]; then
        sleep 0.1
    else
        break
    fi
done
```

**Comment by wwns** [comment]
Restoring SSH access on Zyxel ONU after forcing 2.5G mode

To force 2.5G operation, first set the SFP interface on your router to 2.5G to establish a connection. If you are stuck in a restricted CLI after logging in via SSH and cannot proceed, follow these steps:

Open the Web GUI and perform a reset/reboot of the Zyxel ONU device.

Once the reboot is complete, SSH access should function correctly.

Log in using the twmanu credentials and revert the speed to default.

Tip: Navigating the command tree

Type hal and press Enter to enter the HAL module.

Hal# set speed ?
  auto    auto
  10m     10m
  100m    100m
  200m    200m
  1g      1g
  2.5g    2.5g
  default default
Hal# set speed 2.5g ?
  mode mode
Hal# set speed 2.5g mode ?
  auto    auto
  full    full
  half    half
  default default
Hal# set speed 2.5g mode full


Then, type ? to display all available commands in this section.

This allows you to navigate through the menu levels and easily find the commands you need.

**Comment by csszokolai** [comment]
> ```
> #!/usr/bin/env bash
> # Requirements: sudo apt-get install -y sshpass expect
> 
> HOST="10.10.1.1"
> SSH_USER="admin"
> SSH_PASS="admin"
> CLI_USER="admin"
> CLI_PASS="1234"
> 
> while true; do
> expect <<EOF
>     set timeout 20
>     log_user 0
> 
>     # SSH login (optimized, faster handshake)
>     spawn sshpass -p "${SSH_PASS}" ssh -tt \
>         -o StrictHostKeyChecking=no \
>         -oHostKeyAlgorithms=+ssh-rsa \
>         -o PreferredAuthentications=password \
>         -o PubkeyAuthentication=no \
>         -o GSSAPIAuthentication=no \
>         -o KbdInteractiveAuthentication=no \
>         -o NumberOfPasswordPrompts=1 \
>         -o ConnectionAttempts=1 \
>         -o ConnectTimeout=1 \
>         ${SSH_USER}@${HOST}
> 
>     # Second login (device CLI login)
>     expect {
>         "Login:" {}
>         timeout { exit 1 }
>         eof     { exit 1 }
>     }
>     after 10
>     send -- "${CLI_USER}\r"
> 
>     expect {
>         "Password:" {}
>         "Invalid login name" { exit 1 }
>         timeout { exit 1 }
>         eof     { exit 1 }
>     }
>     after 10
>     send -- "${CLI_PASS}\r"
> 
>     # After CLI login: either already in Hal# prompt or still in ZYXEL# prompt
>     set in_hal 0
>     expect {
>         -re {Hal#}   { set in_hal 1 }
>         -re {ZYXEL#} { set in_hal 0 }
>         timeout { exit 1 }
>         eof     { exit 1 }
>     }
> 
>     log_user 1
> 
>     # Only enter HAL mode if not already in Hal#
>     if { \$in_hal == 0 } {
>         send -- "\r"
>         expect -re {ZYXEL#}
>         send -- "hal\r"
>         expect -re {Hal#}
>     }
> 
>     # Send the target command + extra Enter
>     send -- "set speed default mode default\r"
>     send -- "\r"
>     expect -re {Hal#}
> 
>     # Hand over to interactive mode
>     interact
>     exit 0
> EOF
> 
>     # Retry every 0.1 seconds until successful
>     if [ $? -ne 0 ]; then
>         sleep 0.1
>     else
>         break
>     fi
> done
> ```

It works for me with tp-link MC420L, thank you!
