### ISSUE TITLE
[KiND QUESTiON] FiRMWARE DOWNLOAD AVAiLABiLiTY

### ISSUE THREAD

**Issue by github-tomster** [xvzf/zyxel-gpon-sfp#20]
hello world
there is the following list:
List of software versions
 - V1.00(ABVJ.0)b3s (2020)
 - V1.00(ABVJ.0)b3i (2020)
 - V2.50(ABVJ.0)b1b (2022)

also i found
- V1.00(ABVJ.0)b3v

onboard of my stick.
however is there a place to download these firmwares/software for an offlineupdate 🤷🏻 
and maybe a changelog ❓

**Comment by LIONNNNNN** [comment]
Did you get the latest firmware?

**Comment by github-tomster** [comment]
no i did not.

**Comment by github-tomster** [comment]
it just took some time ⏳ 
https://gist.github.com/maurice-w/faeb60bf8201ce70391873bcb9059bc2

🚀
