### ISSUE TITLE
Unable to use hal/manufactory commands

### ISSUE THREAD

**Issue by jkwpls** [xvzf/zyxel-gpon-sfp#23]
A few months ago I changed the the required serial number and vendor name using `hal` / `manufactory` commands that are required by My ISP and module is working fine without any issues and still is.

In the meantime My ISP started offering 2Gbit speeds and they change routers - requiring me to change the serial number and vendor name once again, in addition with enabling the 2.5G mode.

While waiting for the eventual rollout I decided to SSH into it once more and test the commands, but it results in errors or complete crashes which require me to either restart My router or replug the module itself.

The `manufactory` command results in the following error:
`admin@SFP:~# manufactory`
`/bin/ash: manufactory: not found`

While the `hal` command completely crashes it and usually spews random bits of HEX code behind it:
```
Starting hal
/tmp/egis/eeprom_a0_info is exist!!!

03 04 01 00 00 00 02 00 00 00 00 03 0c 00 14 c8
00 00 00 00 5A 59 58 45 4C 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 50 4D 47 33 30 30 30 2D
44 32 30 42 00 00 00 00 56 31 2E 30 05 1e 00 55
00 1a 00 00 53 32 30 34 31 33 32 35 30 35
```

I don't recall changing anything besides the SN and equipment name so I don't know how I've managed to brick it like that.
Reading the hack-gpon site I did see it has a second image with the same size (currently on mdt2) - so I guess I cloud just switch to mdt3 (image B) and set it up from there?

What would I have to do to fix it, and I someone knows what did I exactly do to cause this?

**Comment by w0vka** [comment]
Hi,

i think you are in the wrong shell. These commands are working as supposed in the default `zyxel shell` and not in the `linuxshell`.
Give it a try without the `linuxshell`.

**Comment by jkwpls** [comment]
> Hi,
> 
> i think you are in the wrong shell. These commands are working as supposed in the default `zyxel shell` and not in the `linuxshell`. Give it a try without the `linuxshell`.

Hi,

Thanks for pointing it out - I did figure it out on my own eventually and completely forgot about opening/closing the issue.

Next time I will attempt not to be a total doofus and read with comprehension.
