### ISSUE TITLE
Cant access SFP after enabling 2.5G

### ISSUE THREAD

**Issue by raumi22** [xvzf/zyxel-gpon-sfp#25]
Hi, cant access the SFP anymore after set 2.5G Mode. 
Have it on a X520-DA2 in PFsense.

Any way to revert this change?

**Comment by raumi22** [comment]
Solved it:

During the boot sequence of the sfp is a short time window where the sfp is running in 1G mode.
Prepeare a brwoser window, when the link is up, fire "http://[IP:Port]/maintenance_reset.html", wait until the page is loading, select "Reset to factory default setting" and click "Apply". 

If you are fast enough, the sfp is rebooting and run with 1G again ;)

**Comment by TDCroPower** [comment]
@xvzf or @slemke76 can you please add the factory reset description from @raumi22 to the 2.5G part or main page?
No Port is needed, only http://10.10.1.1/maintenance_reset.html and login with admin/1234

**Comment by Dmitry-N-Medvedev** [comment]
> Solved it:
> 
> During the boot sequence of the sfp is a short time window where the sfp is running in 1G mode. Prepeare a browser window, when the link is up, fire "http://[IP:Port]/maintenance_reset.html", wait until the page is loaded, select "Reset to factory default setting" and click "Apply".
> 
> If you are fast enough, the sfp is rebooting and run with 1G again ;)

how do I reboot the device?
